### ISSUE TITLE
there are many mismatch between oscm-common  repository and oscm/oscm-common 

### ISSUE THREAD

**Issue by rmros** [servicecatalog/oscm-commons#18]
there are many mismatch between oscm-common  repository and oscm/oscm-common and oscm/oscm-common server,

when i rebuild oscm with imported new fresh or latest commit oscm-common module there are many mismatch and errors,

 Error:(35, 38) java: cannot access javax.servlet.http.HttpServletRequest
  class file for javax.servlet.http.HttpServletRequest not found

**Comment by GoebelL** [comment]
@rmros 
The oscm-common is a dependency of the oscm main repo.  It is resolved by the ANT task Build.LIB (see the readme of the oscm repo).  It seems you have checked out the oscm repo and not build the libraries or your workspace is created longer ago before oscm-commons was externalized.
Check-out the latest master of oscm repo. Run BUILD.LIB to fetch the dependend modules (in particular this target also downloads latest master snapshot of oscm-commons repo and extracts its classes in oscm/oscm-common/javares.)
