### ISSUE TITLE
Remove this repo

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-commons#5]
This utility repo is no longer needed and shall be removed
* oscm-rest-api-common => to be moved in oscm-rest-api  repo
* oscm oscm-common => to be taken from oscm-app repo
* oscm-app-common => to be taken from oscm-app repo 
* oscm-webservices-client => unneeded

**Comment by adamczykba** [comment]
@GoebelL 
*oscm-rest-api-common* will be incorporated into rest repository in scope of https://github.com/servicecatalog/oscm-rest-api/issues/30

**Comment by kowalczyka** [comment]
Closing as this issue is no longer valid because oscm-common will be kept here
