### ISSUE TITLE
Remove Rest API commons

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-commons#6]
**Summary**
Let's remove rest-api-commons module as it has been moved to other repo

**Details**
N/A

**Acceptance criteria**
- [x] OSCM REST API Common module is removed

**Additional context**
N/A

**Comment by kowalczyka** [comment]
This is alredy being handled along with https://github.com/servicecatalog/oscm-app/issues/18. Please check https://github.com/servicecatalog/oscm-commons/tree/task/common_cleanup

**Comment by adamczykba** [comment]
@kowalczyka 
Ok, fine for me then
